- name: Install nginx and python3-cryptography
  apt:
    name:
      - nginx
      - python3-cryptography
    state: present
    update_cache: true

- name: Create directory for certificates
  file:
    path: /etc/nginx/ssl
    state: directory
    mode: '0755'

- name: Create private key
  community.crypto.openssl_privatekey:
    path: /etc/nginx/ssl/nginx.key

- name: Create CSR
  community.crypto.openssl_csr:
    path: /etc/nginx/ssl/nginx.csr
    privatekey_path: /etc/nginx/ssl/nginx.key
    common_name: "mgoral.pl"

- name: Create self-signed certificate
  community.crypto.x509_certificate:
    path: /etc/nginx/ssl/nginx.crt
    privatekey_path: /etc/nginx/ssl/nginx.key
    csr_path: /etc/nginx/ssl/nginx.csr
    provider: selfsigned

- name: Enable and start nginx
  systemd:
    name: nginx
    enabled: true
    state: started

- name: Remove default nginx site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: reload nginx

- name: Deploy nginx vhost config
  template:
    src: web.conf.j2
    dest: /etc/nginx/conf.d/web.conf
    mode: "0644"
  notify: reload nginx

- name: Deploy index.html
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
    mode: "0644"

- name: Deploy maintenance.html page
  template:
    src: maintenance.html.j2
    dest: /var/www/html/maintenance.html
    mode: "0644"

- name: Enable maintenance mode
  file:
    path: /var/www/html/.maintenance
    state: touch
  tags: maintenance_on

- name: Disable maintenance mode
  file:
    path: /var/www/html/.maintenance
    state: absent
  tags: maintenance_off